steps:
  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finance-ai-backend', '-f', 'backend/Dockerfile', '.']

  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finance-ai-frontend', '-f', 'frontend/Dockerfile', 'frontend']

  # Push images to Container Registry (or Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finance-ai-backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finance-ai-frontend']

images:
  - 'gcr.io/$PROJECT_ID/finance-ai-backend'
  - 'gcr.io/$PROJECT_ID/finance-ai-frontend'
